### ISSUE TITLE
instead of circles, there are boxes

### ISSUE THREAD

**Issue by artistic-hacktivist** [tsoding/musializer#1]
I installed all the necessary dependencies and such, and yet this happens:
![issue](https://github.com/tsoding/musializer/assets/127621779/53305fc1-0fcc-447d-ad39-6f081b96ec34)

arch linux btw

**Comment by JosueRhea** [comment]
Same happened to me, but it was a problem with the shader not compiling properly because my machine is very old so it uses and old version of opengl too. So it couldn't compile the shaders. So i downgrade the shaders to use version 1.20 like

```c
// circle.fs
#version 120

// Input vertex attributes (from vertex shader)
varying vec2 fragTexCoord;
varying vec4 fragColor;

// Output fragment color
vec4 finalColor;

void main()
{
    float r = 0.07;
    vec2 p = fragTexCoord - vec2(0.5);
    if (length(p) <= 0.5) {
        float s = length(p) - r;
        if (s <= 0.0) {
            finalColor = fragColor * 1.5;
        } else {
            float t = 1.0 - s / (0.5 - r);
            finalColor = mix(vec4(fragColor.xyz, 0.0), fragColor * 1.5, t*t*t*t*t);
        }
    } else {
        finalColor = vec4(0.0);
    }
    gl_FragColor = finalColor;
}
```
```c
// smear.fs
#version 120

// Input vertex attributes (from vertex shader)
varying vec2 fragTexCoord;
varying vec4 fragColor;

// Output fragment color
vec4 finalColor;

void main()
{
    float r = 0.3;
    vec2 p = fragTexCoord - vec2(0.5);
    if (length(p) <= 0.5) {
        float s = length(p) - r;
        if (s <= 0.0) {
            finalColor = fragColor * 1.5;
        } else {
            float t = 1.0 - s / (0.5 - r);
            finalColor = mix(vec4(fragColor.xyz, 0.0), fragColor * 1.5, t*t*t);
        }
    } else {
        finalColor = vec4(0.0);
    }
    gl_FragColor = finalColor;
}
```

after that it worked. So maybe it's your problem too :)

**Comment by rexim** [comment]
Btw, raylib examples use several versions of shader simultaneously and pick the right version at the runtime. Maybe we should do the same...

**Comment by JosueRhea** [comment]
Yaaaa it shouldn't be that hard to do, so it makes sense...

**Comment by yuI4140** [comment]
> I installed all the necessary dependencies and such, and yet this happens:
> ![issue](https://github.com/tsoding/musializer/assets/127621779/53305fc1-0fcc-447d-ad39-6f081b96ec34)
> 
> arch linux btw

Now is fixed

**Comment by unsubtract** [comment]
This also seems to happen if you run musializer from the `build/` directory instead of the root directory, because the shaders are loaded from a path relative to the root (and you get a file not found if you don't run it this way or manually move the shaders).

**Comment by artistic-hacktivist** [comment]
In the end, the problem (for me at least) was user error. I feel quite silly. I was running from the build directory :P

**Comment by rexim** [comment]
@artistic-hacktivist thanks for letting me know anyway! It may count as a usability issue, that I took a note of.
