### ISSUE TITLE
Build issue: Make readdir, closedir, opendir static in nob.h

### ISSUE THREAD

**Issue by OetkenPurveyorOfCode** [tsoding/musializer#45]
```
raylib.lib(rcore.obj) : error LNK2005: opendir already defined in plug.obj
raylib.lib(rcore.obj) : error LNK2005: closedir already defined in plug.obj
raylib.lib(rcore.obj) : error LNK2005: readdir already defined in plug.obj
```
Both rcore.c and plug.c (via nob.h) export opendir, closedir and readdir. This results in a linker error. I fixed it currently by declaring them static in nob.h.

**Comment by davehorner** [comment]
thank you. I made a PR.  With the static definition changes you suggested I also got a working build!  It just fucking works now.
