### ISSUE TITLE
[Feature] Kind of a playlist mode?

### ISSUE THREAD

**Issue by T-r-y-o-k-s** [tsoding/musializer#50]
Currently Musializer will loop the same track endlessly.
If there are multiple tracks, imo it would be better to play the next track after the current one finished playing. When the last track in the track list finishes, go back to the first one.
This would be similiar to how most music players implement playlists, thus the title.

**Comment by T-r-y-o-k-s** [comment]
OK, I think I did it, so far I haven't noticed any errors and it does what I want it to do.
Because Tsoding [stated](https://github.com/tsoding/musializer/blob/master/CONTRIBUTING.md) he won't look into PRs adding features I don't see the need to create one.
But if you're interested, [here](https://github.com/T-r-y-o-k-s/musializer/tree/playlist_mode) are my changes.

**Comment by rexim** [comment]
But Musializer is not a music player ._.

**Comment by T-r-y-o-k-s** [comment]
OK, closing this suggestion then. But it still was fun figuring out how to do it :)
