### ISSUE TITLE
gmusializer(20953,0x1e2b35b40) malloc: double free for ptr 0x158028000

### ISSUE THREAD

**Issue by wisonye** [tsoding/musializer#64]
Hi, I love all your YouTube videos and was watching your latest one `This Release is Insane!`, then I want to try it by myself. Here are the steps I had tried and then I saw the `double free` bug:

Apple M2 Macbook Air with the following `clang` version:

```bash
clang --version
Homebrew clang version 17.0.6
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

1. Install `ffmpeg` and `raylib 5.0`

2. Compile the project

    ```bash
    # Compile no build without any error
    clang -o nob nob.c

    # Comiple the binary with warnings
    /Users/wison/c/musializer   ./nob

    # [INFO] --- STAGE 1 ---
    # [INFO] created directory `build`
    # [INFO] Generating ./build/config.h
    # [INFO] CMD: cc -o ./build/nob.configured nob.c -DCONFIGURED
    # [INFO] CMD: ./build/nob.configured
    # [INFO] --- STAGE 2 ---
    # [INFO] Target: macos
    # [INFO] Hotreload: DISABLED
    # [INFO] Microphone: DISABLED
    # [INFO] ---
    # [INFO] created directory `./build/raylib`
    # [INFO] created directory `./build/raylib/macos`
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/rcore.c -o ./build/raylib/macos/rcore.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/raudio.c -o ./build/raylib/macos/raudio.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -x objective-c -c ./raylib/raylib-5.0/src/rglfw.c -o ./build/raylib/macos/rglfw.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/rmodels.c -o ./build/raylib/macos/rmodels.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/rshapes.c -o ./build/raylib/macos/rshapes.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/rtext.c -o ./build/raylib/macos/rtext.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/rtextures.c -o ./build/raylib/macos/rtextures.o
    # [INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-5.0/src/utils.c -o ./build/raylib/macos/utils.o
    # In file included from ./raylib/raylib-5.0/src/rmodels.c:111:
    # ./raylib/raylib-5.0/src/external/par_shapes.h:1133:32: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
    #  1133 |     float r = (float) rand() / RAND_MAX;
    #       |                              ~ ^~~~~~~~
    # /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/stdlib.h:105:18: note: expanded from macro 'RAND_MAX'
    #   105 | #define RAND_MAX        0x7fffffff
    #       |                         ^~~~~~~~~~
    # 1 warning generated.
    # [INFO] CMD: ar -crs ./build/raylib/macos/libraylib.a ./build/raylib/macos/rcore.o ./build/raylib/macos/raudio.o ./build/raylib/macos/rglfw.o ./build/raylib/macos/rmodels.o ./build/raylib/macos/rshapes.o ./build/raylib/macos/rtext.o ./build/raylib/macos/rtextures.o ./build/raylib/macos/utils.o
    # [INFO] CMD: clang -Wall -Wextra -g -I./build/ -I./raylib/raylib-5.0/src/ -o ./build/musializer ./src/plug.c ./src/ffmpeg_linux.c ./src/musializer.c ./build/raylib/macos/libraylib.a -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -lm -ldl -lpthread
    # [INFO] created directory `./build/resources/`
    # [INFO] created directory `./build/resources//logo`
    # [INFO] copying ./resources//logo/logo-256.ico -> ./build/resources//logo/logo-256.ico
    # [INFO] copying ./resources//logo/logo-256.png -> ./build/resources//logo/logo-256.png
    # [INFO] copying ./resources//logo/logo.svg -> ./build/resources//logo/logo.svg
    # [INFO] created directory `./build/resources//icons`
    # [INFO] copying ./resources//icons/fullscreen.svg -> ./build/resources//icons/fullscreen.svg
    # [INFO] copying ./resources//icons/volume.png -> ./build/resources//icons/volume.png
    # [INFO] copying ./resources//icons/volume.svg -> ./build/resources//icons/volume.svg
    # [INFO] copying ./resources//icons/fullscreen.png -> ./build/resources//icons/fullscreen.png
    # [INFO] created directory `./build/resources//shaders`
    # [INFO] created directory `./build/resources//shaders/glsl120`
    # [INFO] copying ./resources//shaders/glsl120/circle.fs -> ./build/resources//shaders/glsl120/circle.fs
    # [INFO] created directory `./build/resources//shaders/glsl330`
    # [INFO] copying ./resources//shaders/glsl330/circle.fs -> ./build/resources//shaders/glsl330/circle.fs
    # [INFO] created directory `./build/resources//fonts`
    # [INFO] copying ./resources//fonts/OFL.txt -> ./build/resources//fonts/OFL.txt
    # [INFO] copying ./resources//fonts/Alegreya-Regular.ttf -> ./build/resources//fonts/Alegreya-Regular.ttf


    ls -lht build/
    # total 5696
    # drwxr-xr-x@ 6 wison  staff   192B 22 Dec 09:50 resources/
    # drwxr-xr-x@ 3 wison  staff    96B 22 Dec 09:50 musializer.dSYM/
    # -rwxr-xr-x@ 1 wison  staff   2.7M 22 Dec 09:50 musializer*
    # drwxr-xr-x@ 3 wison  staff    96B 22 Dec 09:50 raylib/
    # -rwxr-xr-x@ 1 wison  staff    69K 22 Dec 09:50 nob.configured*
    # -rw-r--r--@ 1 wison  staff   457B 22 Dec 09:50 config.h
    ```

3. Run it without error

    ```bash
    /Users/wison/c/musializer   ./build/musializer

    # INFO: FILEIO: [./resources/logo/logo-256.png] File loaded successfully
    # INFO: IMAGE: Data loaded successfully (256x256 | R8G8B8A8 | 1 mipmaps)
    # INFO: Initializing raylib 5.0
    # INFO: Platform backend: DESKTOP (GLFW)
    # INFO: Supported raylib modules:
    # INFO:     > rcore:..... loaded (mandatory)
    # INFO:     > rlgl:...... loaded (mandatory)
    # INFO:     > rshapes:... loaded (optional)
    # INFO:     > rtextures:. loaded (optional)
    # INFO:     > rtext:..... loaded (optional)
    # INFO:     > rmodels:... loaded (optional)
    # INFO:     > raudio:.... loaded (optional)
    # INFO: DISPLAY: Device initialized successfully
    # INFO:     > Display size: 1280 x 832
    # INFO:     > Screen size:  1280 x 720
    # INFO:     > Render size:  1280 x 720
    # INFO:     > Viewport offsets: 0, 0
    # INFO: GLAD: OpenGL extensions loaded successfully
    # INFO: GL: Supported extensions count: 43
    # INFO: GL: OpenGL device information:
    # INFO:     > Vendor:   Apple
    # INFO:     > Renderer: Apple M2
    # INFO:     > Version:  4.1 Metal - 83.1
    # INFO:     > GLSL:     4.10
    # INFO: GL: VAO extension detected, VAO functions loaded successfully
    # INFO: GL: NPOT textures extension detected, full NPOT textures supported
    # INFO: GL: DXT compressed textures supported
    # INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
    # INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
    # INFO: TEXTURE: [ID 1] Default texture loaded successfully
    # INFO: SHADER: [ID 1] Vertex shader compiled successfully
    # INFO: SHADER: [ID 2] Fragment shader compiled successfully
    # INFO: SHADER: [ID 3] Program shader loaded successfully
    # INFO: SHADER: [ID 3] Default shader loaded successfully
    # INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
    # INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
    # INFO: RLGL: Default OpenGL state initialized successfully
    # INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
    # INFO: FONT: Default font loaded successfully (224 glyphs)
    # WARNING: GLFW: Error: 65548 Description: Cocoa: Regular windows do not have icons on macOS
    # INFO: TIMER: Target time per frame: 16.667 milliseconds
    # INFO: AUDIO: Device initialized successfully
    # INFO:     > Backend:       miniaudio / Core Audio
    # INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
    # INFO:     > Channels:      2 -> 2
    # INFO:     > Sample rate:   48000 -> 48000
    # INFO:     > Periods size:  1440
    # INFO: FILEIO: [./resources/fonts/Alegreya-Regular.ttf] File loaded successfully
    # INFO: TEXTURE: [ID 3] Texture loaded successfully (1024x512 | GRAY_ALPHA | 1 mipmaps)
    # INFO: FONT: Data loaded successfully (64 pixel size | 95 glyphs)
    # INFO: TEXTURE: [ID 3] Mipmaps generated automatically, total: 11
    # INFO: FILEIO: [./resources/shaders/glsl330/circle.fs] Text file loaded successfully
    # INFO: SHADER: [ID 4] Fragment shader compiled successfully
    # INFO: SHADER: [ID 5] Program shader loaded successfully
    # INFO: TEXTURE: [ID 4] Texture loaded successfully (1600x900 | R8G8B8A8 | 1 mipmaps)
    # INFO: TEXTURE: [ID 1] Depth renderbuffer loaded successfully (32 bits)
    # INFO: FBO: [ID 1] Framebuffer object created successfully
    ```

    
4. Drag&drop 2 MP3 files into the UI, then it crash:

    <img width="1280" alt="running_screenshot" src="https://github.com/tsoding/musializer/assets/3477321/4967f843-3ba2-4ab8-a995-8baf953f5f8b">

    ```bash
    gmusializer(20953,0x1e2b35b40) malloc: double free for ptr 0x158028000
    musializer(20953,0x1e2b35b40) malloc: *** set a breakpoint in malloc_error_break to debug
    fish: Job 1, './build/musializer' terminated by signal SIGABRT (Abort)
    ```

**Comment by wisonye** [comment]
I've already given it another try on Intel iMac as well, same double free issue:

```bash
musializer(7021,0x114acde00) malloc: *** error for object 0x7ff350118000: pointer being freed was not allocated
musializer(7021,0x114acde00) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by wisonye** [comment]
It happens in `Arch Linux` as well...

**Comment by petergr20** [comment]
same thing on ubuntu 

Linux tux 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

./build/musializer 
INFO: FILEIO: [./resources/logo/logo-256.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (256x256 | R8G8B8A8 | 1 mipmaps)
INFO: Initializing raylib 5.0
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  1280 x 720
INFO:     > Render size:  1280 x 720
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 235
INFO: GL: OpenGL device information:
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD Radeon Graphics (raphael_mendocino, LLVM 15.0.7, DRM 3.54, 6.5.0-14-generic)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / PulseAudio
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit Signed Integer
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  3600
INFO: FILEIO: [./resources/fonts/Alegreya-Regular.ttf] File loaded successfully
INFO: TEXTURE: [ID 3] Texture loaded successfully (1024x512 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Data loaded successfully (64 pixel size | 95 glyphs)
INFO: TEXTURE: [ID 3] Mipmaps generated automatically, total: 11
INFO: FILEIO: [./resources/shaders/glsl330/circle.fs] Text file loaded successfully
INFO: SHADER: [ID 4] Fragment shader compiled successfully
INFO: SHADER: [ID 5] Program shader loaded successfully
INFO: TEXTURE: [ID 4] Texture loaded successfully (1600x900 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Depth renderbuffer loaded successfully (32 bits)
INFO: FBO: [ID 1] Framebuffer object created successfully

free(): double free detected in tcache 2
Aborted (core dumped)

file build/musializer 
build/musializer: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=aac14e731ee5a88467b3667d1da784831d0617e3, for GNU/Linux 3.2.0, with debug_info, not stripped

log of the end of strace

strace ./build/musializer  
....

read(19, "\224F\320\1r\2\0\0\32I\320\1\n\2\0\0,K\320\1r\2\0\0\262M\320\1r\2\0\0"..., 4096) = 4096
read(19, "\220x\325\1C\3\0\0\350{\325\1C\3\0\0@\177\325\1\n\2\0\0R\201\325\1\n\2\0\0"..., 61440) = 61440
read(19, "\250[#\2r\2\0\0.^#\2\333\2\0\0\22a#\2\n\2\0\0000c#\2\n\2\0\0"..., 4096) = 4096
read(19, "\242\224(\2\n\2\0\0\300\226(\2r\2\0\0F\231(\2r\2\0\0\300\233(\2r\2\0\0"..., 61440) = 48304
read(19, "", 16384)                     = 0
read(19, "", 65536)                     = 0
close(19)                               = 0
writev(2, [{iov_base="free(): double free detected in "..., iov_len=40}, {iov_base="\n", iov_len=1}], 2free(): double free detected in tcache 2
) = 41
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fedae473000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
gettid()                                = 15061
getpid()                                = 15061
tgkill(15061, 15061, SIGABRT)           = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=15061, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)

**Comment by rexim** [comment]
Is this problem still reproducible? I could not reproduce it either on my Debian or Window setup.

**Comment by petergr20** [comment]
Yes absolutely

***@***.***:~/Develop/musializer$ ./build/musializer
INFO: FILEIO: [./resources/logo/logo-256.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (256x256 | R8G8B8A8 | 1 mipmaps)
INFO: Initializing raylib 5.0
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 3440 x 1440
INFO:     > Screen size:  1280 x 720
INFO:     > Render size:  1280 x 720
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 235
INFO: GL: OpenGL device information:
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD Radeon Graphics (raphael_mendocino, LLVM 15.0.7,
DRM 3.54, 6.5.0-15-generic)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1
mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1
mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / PulseAudio
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit Signed
Integer
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  3600
INFO: FILEIO: [./resources/fonts/Alegreya-Regular.ttf] File loaded
successfully
INFO: TEXTURE: [ID 3] Texture loaded successfully (1024x512 | GRAY_ALPHA |
1 mipmaps)
INFO: FONT: Data loaded successfully (64 pixel size | 95 glyphs)
INFO: TEXTURE: [ID 3] Mipmaps generated automatically, total: 11
INFO: FILEIO: [./resources/shaders/glsl330/circle.fs] Text file loaded
successfully
INFO: SHADER: [ID 4] Fragment shader compiled successfully
INFO: SHADER: [ID 5] Program shader loaded successfully
INFO: TEXTURE: [ID 4] Texture loaded successfully (1600x900 | R8G8B8A8 | 1
mipmaps)
INFO: TEXTURE: [ID 1] Depth renderbuffer loaded successfully (32 bits)
INFO: FBO: [ID 1] Framebuffer object created successfully
free(): double free detected in tcache 2
Abandon (core dumped)

***@***.***:~/Develop/musializer$ file build/musializer
build/musializer: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV),
dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2,
BuildID[sha1]=1f9c221cb790d7e0c9f18cf936a445979959f998, for GNU/Linux
3.2.0, with debug_info, not stripped

nob: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically
linked, interpreter /lib64/ld-linux-x86-64.so.2,
BuildID[sha1]=684f4474100e0fc831498a1c5dbe0db07ea74f14, for GNU/Linux
3.2.0, not stripped


CPU: 12-core AMD Ryzen 9 7900 (-MT MCP-) speed/min/max: 1879/400/5482 MHz
Kernel: 6.5.0-15-generic x86_64 Up: 2d 4h 41m Mem: 5.58/30.55 GiB (18.3%)

Linux tux 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9
17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

***@***.***:~/Develop/musializer$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu
13.2.0-4ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs
--enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr
--with-gcc-major-version-only --program-suffix=-13
--program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id
--libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix
--libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu
--enable-libstdcxx-debug --enable-libstdcxx-time=yes
--with-default-libstdcxx-abi=new --enable-gnu-unique-object
--disable-vtable-verify --enable-plugin --enable-default-pie
--with-system-zlib --enable-libphobos-checking=release
--with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch
--disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64
--with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic
--enable-offload-targets=nvptx-none=/build/gcc-13-XYspKM/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-XYspKM/gcc-13-13.2.0/debian/tmp-gcn/usr
--enable-offload-defaulted --without-cuda-driver --enable-checking=release
--build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
--with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3)

Hope this help you and i'm a big fon of your video  👍




Le jeu. 8 févr. 2024 à 13:14, Alexey Kutepov ***@***.***> a
écrit :

**Comment by petergr20** [comment]
I'm trying with raylib-4.5.0 in nob.c and same result  ;-(

INFO: FBO: [ID 1] Framebuffer object created successfully
free(): double free detected in tcache 2
Abandon (core dumped)

**Comment by jgabaut** [comment]
@wisonye 
> It happens in `Arch Linux` as well...

Can't reproduce this on `Arch Linux` from a fresh build with `raylib 5.0`.

```console
$ uname -r
6.7.4-arch1-1
```

**Comment by petergr20** [comment]
works file now thx

![Capture d’écran du 2024-02-25 21-18-08](https://github.com/tsoding/musializer/assets/95576983/c7a3f69e-fcfe-46a2-8ed3-2e0f24f35cac)

**Comment by rexim** [comment]
Cool
