### ISSUE TITLE
Fullscreen flag needed only for me?

### ISSUE THREAD

**Issue by JaroslawWiosna** [tsoding/musializer#7]
Hi! I was about to maximize the window, but I couldn't

I had to:

```
-    SetConfigFlags(FLAG_MSAA_4X_HINT);
+    SetConfigFlags(FLAG_WINDOW_RESIZABLE | FLAG_MSAA_4X_HINT);
```

and now I can experience your awesome masterpiece in full screen :)

---

I just wonder if your powerful i3 setup doesn't require this flag?

**Comment by rexim** [comment]
Weirdly enough, $mod+f puts in fullscreen any window even non-resizable one. It's a good flag to have tho. Feel free to submit a PR.

**Comment by yuI4140** [comment]
> Hi! I was about to maximize the window, but I couldn't
> 
> I had to:
> 
> ```
> -    SetConfigFlags(FLAG_MSAA_4X_HINT);
> +    SetConfigFlags(FLAG_WINDOW_RESIZABLE | FLAG_MSAA_4X_HINT);
> ```
> 
> and now I can experience your awesome masterpiece in full screen :)
> 
> I just wonder if your powerful i3 setup doesn't require this flag?

you can add this command in your I3 config for do full screen `bindsym $mod+f fullscreen toggle`

**Comment by T-r-y-o-k-s** [comment]
> Hi! I was about to maximize the window, but I couldn't
> 
> I had to:
> 
> ```
> -    SetConfigFlags(FLAG_MSAA_4X_HINT);
> +    SetConfigFlags(FLAG_WINDOW_RESIZABLE | FLAG_MSAA_4X_HINT);
> ```
> 
> and now I can experience your awesome masterpiece in full screen :)
> 
> I just wonder if your powerful i3 setup doesn't require this flag?

This is also necessary when compiling for Windows.

**Comment by unsubtract** [comment]
I'm also unable to resize the window without the flag (Xfce)

**Comment by yuI4140** [comment]
> I'm also unable to resize the window without the flag (Xfce)

you have a keybind for full screen? if so you could use it with it tho
