### ISSUE TITLE
Cannot load file

### ISSUE THREAD

**Issue by Pandetthe** [tsoding/musializer#9]
When music file name contains language specific characters (non ascii), app shows that it could not load file.
Example chars: ł, ą, ó, ś, ć

**Comment by rexim** [comment]
It's Windows, right?

**Comment by Pandetthe** [comment]
Yes

**Comment by bagasjs** [comment]
I also have an issue related to file loading where certain files will resulting this error
`free(): double free detected in tcache 2`

**Comment by OetkenPurveyorOfCode** [comment]
I fixed the problem of loading the file: "Fix for issue #9: Change the Codepage of the process to UTF-8 #42". But in the UI the Unicode characters render as underscores.
